SELECT PROC
    ; SORTS A BYTE ARRAY BY THE SELECTION SORT
    ; INPUT: SI = ARRAY OFFSET ADDRESS AND BX= NUMBER OF ELEMENTS
    ; OUTPUT: SI = OFFSET OF SORTED ARRAY
    ; USES: SWAP
    
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH SI
    
    DEC BX ; WE NEED TO FIND THE LARGEST AMONG 1RST N - 1 ELEMENT
    JE END_SORT
    
    MOV DX, SI
    ; FOR N-1 TIMES DO
    
    SORT_LOOP:
    MOV SI, DX
    MOV CX, BX
    MOV DI, SI
    MOV AL,[DI]
    
    FIND_BIG:
    INC SI
    CMP [SI], AL
    JLE NEXT  ;; MAKE JGE TO SORT IN REVERSE
    MOV DI, SI
    MOV AL,[DI]
    
    NEXT:
    LOOP FIND_BIG
    ;SWAP THE BIGGEST WITH THE LAST
    CALL SWAP
    DEC BX
    JNE SORT_LOOP
    END_SORT:
    POP SI
    POP DX
    POP CX
    POP BX
    RET
    SELECT ENDP
SWAP PROC
    ;SWAPS TWO ARRAY ELEMENTS
    ;INPUT: SI = ONE ELEMENT AND DI = OTHER ELEMENTS
    ;OUTPUT: EXCHANGE-ELEMENTS
    
    PUSH AX
    MOV AL, [SI]
    XCHG AL, [DI]
    MOV [SI], AL
    POP AX
    RET
    SWAP ENDP